
---
- name: Serverni sozlash
  hosts: all
  become: yes
  tasks:
    # 1. Yangi qo'shilgan tool (Git)
    - name: Git o'rnatish
      apt:
        name: git
        state: present
        update_cache: yes

    # 2. Mavjud bo'lgan Nginx qismi
    - name: Nginx o'rnatish
      apt:
        name: nginx
        state: present

    - name: Nginx xizmatini yoqish
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install basic tools
      apt:
        name:
          - curl
          - htop
        state: present    

        
