
---
- name: Serverni sozlash
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install env-specific packages
      apt:
        name: "{{ packages }}"
        state: present

    - name: Nginx xizmatini yoqish
      service:
        name: nginx
        state: started
        enabled: yes
        
