name: Smart Deploy

on:
  push:
    branches:
      - main
      - preprod
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Deploy via Bastion
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -x

            cd ~/ansible-project || exit 1
            git pull

            BRANCH="${{ github.ref_name }}"
            echo "Branch: $BRANCH"

            if [ "$BRANCH" = "test" ]; then
              TARGET="test"
            elif [ "$BRANCH" = "preprod" ]; then
              TARGET="preprod"
            else
              echo "Unknown branch"
              exit 1
            fi

            echo "Deploying to $TARGET"

            ansible-playbook -i inventory/$TARGET.ini playbooks/site.yml
