name: Ansible Deploy
on:
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Playbook fayli yo\'li'
        required: true
        default: 'playbooks/site.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SSH and Run
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/ansible-project
            git pull origin main
            # Agar playbook nomi kiritilmagan bo'lsa, default ishlatiladi
            ansible-playbook -i inventory/host.ini ${{ github.event.inputs.playbook || 'playbooks/site.yaml' }}
