name: Ansible CD Pipeline

on:
  # 1. Kod push bo'lganda avtomatik 'site.yaml' ishga tushadi
  push:
    branches: [ main ]
    paths:
      - 'playbooks/**'
      - 'inventory/**'

  # 2. GitHub interfeysidan xohlagan playbookni tanlab run qilish
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Ishga tushiriladigan playbook yo‘li'
        required: true
        default: 'playbooks/site.yaml'
        type: string
      target_limit:
        description: 'Qaysi serverlarga? (test, preprod yoki all)'
        required: true
        default: 'all'
        type: string

jobs:
  ansible-task:
    runs-on: self-hosted  # Sizda tayyor turgan runnerdan foydalanamiz
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: |
          # Dinamik o'zgaruvchilarni aniqlash
          PLAYBOOK_FILE="${{ github.event.inputs.playbook || 'playbooks/site.yaml' }}"
          LIMIT_HOSTS="${{ github.event.inputs.target_limit || 'all' }}"
          
          echo "Ishga tushmoqda: $PLAYBOOK_FILE (Serverlar: $LIMIT_HOSTS)"
          
          # Ansible buyrug'i
          ansible-playbook -i inventory/host.ini $PLAYBOOK_FILE --limit "$LIMIT_HOSTS"
