name: Smart Deploy

on:
  push:
    branches:
      - main
      - preprod
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Deploy via Bastion
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -x

            cd ~/ansible-project || exit 1
            git pull

            # GitHub-dan joriy branch nomini olamiz
            BRANCH="${{ github.ref_name }}"
            echo "Branch: $BRANCH"

            # Branchga qarab Targetni aniqlash
            if [ "$BRANCH" = "test" ]; then
              TARGET="test"
            elif [ "$BRANCH" = "preprod" ]; then
              TARGET="preprod"
            elif [ "$BRANCH" = "main" ]; then
              TARGET="main"  # Agar inventory ichida main.ini bo'lsa
            else
              echo "Unknown branch: $BRANCH"
              exit 1
            fi

            echo "Deploying to $TARGET"

            # Ansible-ni ishga tushirish
            ansible-playbook -i inventory/$TARGET.ini playbooks/site.yaml
            ansible-playbook -i inventory/hosts.ini playbooks/install-tools.yaml -l $TARGET
            ansible-playbook -i inventory/hosts.ini playbooks/extra-tools.yaml -l $TARGET
            
