name: Smart Deploy

on:
  push:
    branches:
      - main
      - preprod
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Deploy via Bastion
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            cd ~/ansible-project
            git pull

            if [ "${{ github.ref_name }}" == "test" ]; then
              ansible-playbook -i inventory/hosts.ini playbooks/install-tools.yml -l test
            elif [ "${{ github.ref_name }}" == "preprod" ]; then
              ansible-playbook -i inventory/hosts.ini playbooks/install-tools.yml -l preprod
            elif [ "${{ github.ref_name }}" == "main" ]; then
              ansible-playbook -i inventory/hosts.ini playbooks/install-tools.yml -l prod
            fi
